import { sql } from 'drizzle-orm'
import {
  bigserial,
  boolean,
  doublePrecision,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core'
import { user } from './auth-schema.js'

/**
 * Better Auth owns `user`, `session`, `account`, `verification`
 * (./auth-schema.ts, generated by `@better-auth/cli` — do not hand-edit, see
 * apps/server/better-auth.config.ts). Everything below is domain-owned and
 * references `user.id` where identity matters.
 */

export const workspace = pgTable(
  'workspace',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('workspace_slug_idx').on(t.slug)],
)

export const workspaceMember = pgTable(
  'workspace_member',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    role: text('role').notNull().default('member'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('workspace_member_unique_idx').on(t.workspaceId, t.userId)],
)

export const channel = pgTable(
  'channel',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    topic: text('topic'),
    isPrivate: boolean('is_private').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('channel_workspace_name_idx').on(t.workspaceId, t.name)],
)

export const thread = pgTable(
  'thread',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    channelId: uuid('channel_id')
      .notNull()
      .references(() => channel.id, { onDelete: 'cascade' }),
    parentMessageId: uuid('parent_message_id'),
    isRoot: boolean('is_root').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('thread_channel_idx').on(t.workspaceId, t.channelId),
    // At most one root thread per channel, enforced in the database.
    uniqueIndex('thread_root_per_channel_idx')
      .on(t.channelId)
      .where(sql`${t.isRoot}`),
  ],
)

/** A paired local daemon (PLAN.md §4a). `allowedRoots` is Runner-declared, not server-managed. */
export const runner = pgTable(
  'runner',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    // Hashed, not raw — a leaked DB row must not itself be a usable pairing token.
    pairingTokenHash: text('pairing_token_hash').notNull(),
    allowedRoots: jsonb('allowed_roots').$type<string[]>().notNull().default([]),
    connected: boolean('connected').notNull().default(false),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('runner_workspace_idx').on(t.workspaceId),
    uniqueIndex('runner_pairing_token_hash_idx').on(t.pairingTokenHash),
  ],
)

/** Phase 1 scope cut (PLAN.md §5a): bound by absolute path, no directory picker or `git init` flow yet. */
export const repository = pgTable(
  'repository',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    runnerId: uuid('runner_id')
      .notNull()
      .references(() => runner.id, { onDelete: 'cascade' }),
    displayName: text('display_name').notNull(),
    absolutePath: text('absolute_path').notNull(),
    defaultBranch: text('default_branch').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('repository_workspace_idx').on(t.workspaceId)],
)

/**
 * `persona` is inline JSON for Phase 1 — no markdown/git-backed persona
 * storage yet (PLAN.md §4/§4e describe the eventual format).
 */
export const agentRun = pgTable(
  'agent_run',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    threadId: uuid('thread_id')
      .notNull()
      .references(() => thread.id, { onDelete: 'cascade' }),
    repositoryId: uuid('repository_id')
      .notNull()
      .references(() => repository.id, { onDelete: 'cascade' }),
    runnerId: uuid('runner_id')
      .notNull()
      .references(() => runner.id, { onDelete: 'cascade' }),
    persona: jsonb('persona').notNull(),
    status: text('status').notNull().default('pending'),
    totalCostUsd: doublePrecision('total_cost_usd'),
    errorMessage: text('error_message'),
    // Set once the Runner finishes cloning (PLAN.md §5a) — null until then,
    // and for any run that fails before a workspace is ever prepared.
    clonePath: text('clone_path'),
    branchName: text('branch_name'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
  },
  (t) => [index('agent_run_thread_idx').on(t.workspaceId, t.threadId)],
)

/**
 * Persona storage (PLAN.md §4e, Phase 1 subset — read/CRUD only, no
 * git-backed versioning yet, per HANDOFF.md). `markdownSource` is the source
 * of truth; the other columns are its parsed frontmatter, denormalized for
 * querying without re-parsing on every list/get.
 */
export const agentPersona = pgTable(
  'agent_persona',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    description: text('description').notNull(),
    markdownSource: text('markdown_source').notNull(),
    model: text('model').notNull(),
    tools: jsonb('tools').$type<string[]>().notNull().default([]),
    harnessEffort: text('harness_effort'),
    harnessMaxTurns: doublePrecision('harness_max_turns'),
    harnessAutoApprove: boolean('harness_auto_approve').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('agent_persona_workspace_idx').on(t.workspaceId),
    uniqueIndex('agent_persona_workspace_name_idx').on(t.workspaceId, t.name),
  ],
)

/**
 * Organizational persona grouping (PLAN.md §3a) — a jsonb array of member
 * persona ids, same convention as `agentPersona.tools`. No join table: there
 * is no per-attachment metadata, unlike `persona_capability` (§4e, Phase 2).
 */
export const personaGroup = pgTable(
  'persona_group',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    personaIds: jsonb('persona_ids').$type<string[]>().notNull().default([]),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('persona_group_workspace_idx').on(t.workspaceId),
    uniqueIndex('persona_group_workspace_name_idx').on(t.workspaceId, t.name),
  ],
)

/**
 * `toolName`/`input` are the exact argv the SDK is about to run — never a
 * model-authored summary (PLAN.md §6 A1/A3). `resolvedBy` must be a `user`
 * actor; enforced in the use-case, not the schema.
 */
export const approvalRequest = pgTable(
  'approval_request',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    agentRunId: uuid('agent_run_id')
      .notNull()
      .references(() => agentRun.id, { onDelete: 'cascade' }),
    toolUseId: text('tool_use_id').notNull(),
    toolName: text('tool_name').notNull(),
    input: jsonb('input').notNull(),
    status: text('status').notNull().default('pending'),
    // No hard FK, deliberately: same reasoning as the actor columns above —
    // devAuth-based tests use synthetic user ids never inserted into
    // Better Auth's `user` table, and a resolver's identity here is an audit
    // fact that must survive even if the referenced user is later removed.
    resolvedByUserId: text('resolved_by_user_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  },
  (t) => [
    index('approval_request_run_idx').on(t.agentRunId),
    uniqueIndex('approval_request_tool_use_idx').on(t.agentRunId, t.toolUseId),
  ],
)

/**
 * `seq` is the ordering and pagination key. Timestamps collide under concurrent
 * inserts, so cursors must never be built from `created_at`.
 */
export const message = pgTable(
  'message',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    seq: bigserial('seq', { mode: 'bigint' }).notNull(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    threadId: uuid('thread_id')
      .notNull()
      .references(() => thread.id, { onDelete: 'cascade' }),
    // Polymorphic actor columns, deliberately without a hard FK on either side
    // (mirrors audit_event below): a cascade delete on `agent_run` or `user`
    // must not silently corrupt chat history. Consistency is enforced in the
    // mapper layer (packages/db/src/mappers.ts toActor/fromActor).
    actorKind: text('actor_kind').notNull(),
    actorUserId: text('actor_user_id'),
    actorAgentRunId: uuid('actor_agent_run_id'),
    bodyKind: text('body_kind').notNull(),
    bodyText: text('body_text').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    editedAt: timestamp('edited_at', { withTimezone: true }),
  },
  (t) => [
    index('message_thread_seq_idx').on(t.workspaceId, t.threadId, t.seq),
    uniqueIndex('message_seq_idx').on(t.seq),
  ],
)

/** Append-only. No update or delete path exists by design (PLAN.md §5). */
export const auditEvent = pgTable(
  'audit_event',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    seq: bigserial('seq', { mode: 'bigint' }).notNull(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    actorKind: text('actor_kind').notNull(),
    actorUserId: text('actor_user_id'),
    actorAgentRunId: uuid('actor_agent_run_id'),
    action: text('action').notNull(),
    subjectType: text('subject_type').notNull(),
    subjectId: text('subject_id').notNull(),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('audit_workspace_seq_idx').on(t.workspaceId, t.seq)],
)
