import { sql } from 'drizzle-orm'
import {
 bigserial,
 boolean,
 doublePrecision,
 index,
 integer,
 jsonb,
 pgTable,
 text,
 timestamp,
 uniqueIndex,
 uuid,
 type AnyPgColumn,
} from 'drizzle-orm/pg-core'
import { user } from './auth-schema.js'

/**
 * Better Auth owns `user`, `session`, `account`, `verification`
 * (./auth-schema.ts, generated by `@better-auth/cli` — do not hand-edit, see
 * apps/server/better-auth.config.ts). Everything below is domain-owned and
 * references `user.id` where identity matters.
 */

export const workspace = pgTable(
 'workspace',
 {
 id: uuid('id').primaryKey.defaultRandom,
 name: text('name').notNull,
 slug: text('slug').notNull,
 // Global kill switch. Persisted rather than
 // held in memory so a pause survives a server restart — an operator who
 // stopped everything must not have it silently undone by a redeploy.
 runsPaused: boolean('runs_paused').notNull.default(false),
 runsPausedAt: timestamp('runs_paused_at', { withTimezone: true }),
 // No hard FK, same reasoning as approvalRequest.resolvedByUserId: who hit
 // the switch is an audit fact that must survive the user being removed.
 runsPausedByUserId: text('runs_paused_by_user_id'),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [uniqueIndex('workspace_slug_idx').on(t.slug)],
)

export const workspaceMember = pgTable(
 'workspace_member',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 userId: text('user_id')
.notNull
.references( => user.id, { onDelete: 'cascade' }),
 role: text('role').notNull.default('member'),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [uniqueIndex('workspace_member_unique_idx').on(t.workspaceId, t.userId)],
)

export const channel = pgTable(
 'channel',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 name: text('name').notNull,
 topic: text('topic'),
 isPrivate: boolean('is_private').notNull.default(false),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [uniqueIndex('channel_workspace_name_idx').on(t.workspaceId, t.name)],
)

export const thread = pgTable(
 'thread',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 channelId: uuid('channel_id')
.notNull
.references( => channel.id, { onDelete: 'cascade' }),
 parentMessageId: uuid('parent_message_id'),
 isRoot: boolean('is_root').notNull.default(false),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [
 index('thread_channel_idx').on(t.workspaceId, t.channelId),
 // At most one root thread per channel, enforced in the database.
 uniqueIndex('thread_root_per_channel_idx')
.on(t.channelId)
.where(sql`${t.isRoot}`),
 ],
)

/** A paired local daemon. `allowedRoots` is Runner-declared, not server-managed. */
export const runner = pgTable(
 'runner',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 name: text('name').notNull,
 // Hashed, not raw — a leaked DB row must not itself be a usable pairing token.
 pairingTokenHash: text('pairing_token_hash').notNull,
 allowedRoots: jsonb('allowed_roots').$type<string[]>.notNull.default([]),
 connected: boolean('connected').notNull.default(false),
 lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [
 index('runner_workspace_idx').on(t.workspaceId),
 uniqueIndex('runner_pairing_token_hash_idx').on(t.pairingTokenHash),
 ],
)

/** Phase 1 scope cut: bound by absolute path, no directory picker or `git init` flow yet. */
export const repository = pgTable(
 'repository',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 runnerId: uuid('runner_id')
.notNull
.references( => runner.id, { onDelete: 'cascade' }),
 displayName: text('display_name').notNull,
 absolutePath: text('absolute_path').notNull,
 defaultBranch: text('default_branch').notNull,
 // What the merge queue runs against a rebased branch before merging it
 //. Null merges unverified — see
 // `planMergeVerification`, which also explains why this executes in the
 // sandbox: the command is the operator's, but the code it runs is the
 // agent's.
 verifyCommand: text('verify_command'),
 // What the platform runs to warm this repository's dependency cache.
 // Operator-authored and run with no agent involved — that is what makes the warmed
 // cache safe to hand to runs, since nothing a model produced ever wrote to it.
 installCommand: text('install_command'),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [index('repository_workspace_idx').on(t.workspaceId)],
)

/**
 * `persona` is inline JSON for Phase 1 — no markdown/git-backed persona
 * storage yet.
 */
export const agentRun = pgTable(
 'agent_run',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 threadId: uuid('thread_id')
.notNull
.references( => thread.id, { onDelete: 'cascade' }),
 repositoryId: uuid('repository_id')
.notNull
.references( => repository.id, { onDelete: 'cascade' }),
 runnerId: uuid('runner_id')
.notNull
.references( => runner.id, { onDelete: 'cascade' }),
 persona: jsonb('persona').notNull,
 // Swarm structure. Null for a run a human started.
 // `relation` distinguishes delegation from review/reconcile, which the data model is
 // explicit should not masquerade as delegation children. Self-referencing FK
 // declared via a callback because the table is still being defined here.
 parentRunId: uuid('parent_run_id').references(: AnyPgColumn => agentRun.id, {
 onDelete: 'cascade',
 }),
 relation: text('relation'),
 // What this run was asked to do. Persisted
 // because a re-planning turn needs the original goal and the current plan, and
 // the task had until now only ever been dispatched to the Runner. Nullable: a run
 // started from the sidebar picker has no task, and every row written before this
 // column existed has none either.
 task: text('task'),
 status: text('status').notNull.default('pending'),
 totalCostUsd: doublePrecision('total_cost_usd'),
 errorMessage: text('error_message'),
 // Set once the Runner finishes cloning — null until then,
 // and for any run that fails before a workspace is ever prepared.
 clonePath: text('clone_path'),
 branchName: text('branch_name'),
 // Set by a human's end-of-run keep/discard decision on DiffView — null until then. `discarded` also implies the
 // clone on disk has been removed by the Runner.
 branchDisposition: text('branch_disposition'),
 // Dead-run reaper inputs — internal-only,
 // never exposed through the contract. `lastHeartbeatAt` is bumped only by
 // the Runner's periodic heartbeat frame (detects a dead connection);
 // `lastEventAt` is bumped by any agent_event (detects a hung-but-connected
 // run). Both null until first arrival — the reaper falls back to
 // `createdAt` so a run that never gets a first heartbeat/event is still
 // caught, not ignored forever.
 lastHeartbeatAt: timestamp('last_heartbeat_at', { withTimezone: true }),
 lastEventAt: timestamp('last_event_at', { withTimezone: true }),
 // Context-window occupancy, sampled by the Runner from the SDK and carried on the
 // heartbeat. Stored on
 // the run rather than as an event: only the *latest* figure means anything, and
 // keeping it here is what lets the board read it without a query of its own.
 // Both null until a Runner samples one — which never happens before the first turn.
 contextTokens: integer('context_tokens'),
 contextMaxTokens: integer('context_max_tokens'),
 // Claimed by whichever sibling reports this run's plan. The claim is the point, not the timestamp: "only the last sibling
 // reports" was a read-then-write with no claim, so two children reaching a
 // terminal status at the same moment both read "all terminal" and both posted.
 // Observed in the dev workspace as a byte-identical duplicate summary.
 aggregatedAt: timestamp('aggregated_at', { withTimezone: true }),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 completedAt: timestamp('completed_at', { withTimezone: true }),
 },
 (t) => [
 index('agent_run_thread_idx').on(t.workspaceId, t.threadId),
 // Backs the tree view's per-parent lookup.
 index('agent_run_parent_idx').on(t.workspaceId, t.parentRunId),
 ],
)

/**
 * The structured event tier, doubling as the idempotency ledger for event ingest (the security model runtime
 * safety: "idempotency keys on run steps").
 *
 * `seq` is a per-run counter the Runner assigns. The unique index on
 * (agent_run_id, seq) is the whole mechanism: a retransmitted or replayed event
 * conflicts, the insert no-ops, and `recordAgentEvent` skips it — so a
 * reconnect can never double-append the same tool call into a thread.
 *
 * Deliberately not the stream-only tier: token deltas and partial reasoning
 * never reach here, and the verbatim provider transcript is a separate
 * blob-storage concern that is still deferred past Phase 1.
 */
export const agentRunEvent = pgTable(
 'agent_run_event',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 agentRunId: uuid('agent_run_id')
.notNull
.references( => agentRun.id, { onDelete: 'cascade' }),
 seq: integer('seq').notNull,
 kind: text('kind').notNull,
 payload: jsonb('payload').notNull,
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [
 uniqueIndex('agent_run_event_run_seq_idx').on(t.agentRunId, t.seq),
 index('agent_run_event_workspace_run_idx').on(t.workspaceId, t.agentRunId, t.seq),
 ],
)

/**
 * The serialized merge queue. One row per branch a
 * human queued for merge into its repository's default branch.
 *
 * Two indexes carry the invariants rather than leaving them to application code:
 *
 * - `merge_queue_active_per_repo_idx` — **at most one `merging` entry per
 * repository**. This is the serialization, and it is here rather than in the
 * sweep because two servers sweeping concurrently would both read the same
 * queued entry and both try to claim it. One insert wins; the other's claim
 * fails, which is exactly right.
 * - `merge_queue_open_per_run_idx` — a run may have at most one *open* entry, so
 * double-clicking Merge cannot queue the same branch twice. Terminal entries are
 * exempt: a branch that failed and was re-queued is a second, legitimate attempt.
 *
 * `position` is a bigserial for the reason `message.seq` is: a swarm's siblings are
 * queued in the same millisecond, so `created_at` cannot order them.
 */
export const mergeQueueEntry = pgTable(
 'merge_queue_entry',
 {
 id: uuid('id').primaryKey.defaultRandom,
 position: bigserial('position', { mode: 'bigint' }).notNull,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 repositoryId: uuid('repository_id')
.notNull
.references( => repository.id, { onDelete: 'cascade' }),
 agentRunId: uuid('agent_run_id')
.notNull
.references( => agentRun.id, { onDelete: 'cascade' }),
 // Snapshotted at enqueue time, so an entry still says which branch it was
 // about even after the run's own row changes underneath it.
 branchName: text('branch_name').notNull,
 status: text('status').notNull.default('queued'),
 failureReason: text('failure_reason'),
 detail: text('detail'),
 mergedCommitSha: text('merged_commit_sha'),
 // Whether a verification command actually ran and passed — not whether one was
 // configured. A repository with no command merges unverified, and this says so.
 verified: boolean('verified').notNull.default(false),
 // No hard FK, same convention as approvalRequest.resolvedByUserId: who queued a
 // merge is an audit fact that must survive the user being removed.
 enqueuedByUserId: text('enqueued_by_user_id'),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 startedAt: timestamp('started_at', { withTimezone: true }),
 finishedAt: timestamp('finished_at', { withTimezone: true }),
 },
 (t) => [
 index('merge_queue_repo_idx').on(t.workspaceId, t.repositoryId, t.position),
 uniqueIndex('merge_queue_active_per_repo_idx')
.on(t.repositoryId)
.where(sql`${t.status} = 'merging'`),
 uniqueIndex('merge_queue_open_per_run_idx')
.on(t.agentRunId)
.where(sql`${t.status} in ('queued', 'merging')`),
 ],
)

/**
 * Persona storage. `markdownSource` is the source
 * of truth; the other columns are its parsed frontmatter, denormalized for
 * querying without re-parsing on every list/get.
 */
export const agentPersona = pgTable(
 'agent_persona',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 name: text('name').notNull,
 description: text('description').notNull,
 markdownSource: text('markdown_source').notNull,
 model: text('model').notNull,
 tools: jsonb('tools').$type<string[]>.notNull.default([]),
 harnessEffort: text('harness_effort'),
 harnessMaxTurns: doublePrecision('harness_max_turns'),
 /**
 * How much a run of this persona may do without asking. Replaces `harness_auto_approve`, whose
 * two states were this column's outer two — a boolean cannot express the middle
 * an operator actually wants, and three call sites compared it.
 */
 harnessApprovalMode: text('harness_approval_mode').notNull.default('ask'),
 // Phase 2. A planner persona gets the delegation tool and is
 // required to declare `tools: []` — enforced in the use-case, not here.
 harnessPlanner: boolean('harness_planner').notNull.default(false),
 // A planner's delegation envelope. Its own `tools` stay empty.
 harnessDelegates: jsonb('harness_delegates').$type<string[]>.notNull.default([]),
 // Enforced at the egress proxy, not advisory. Null = uncapped.
 harnessBudgetCapUsd: doublePrecision('harness_budget_cap_usd'),
 /**
 * The markdown **the platform seeded**, verbatim, for a built-in.
 * Null on a hand-authored persona, and on a built-in seeded before this column
 * existed.
 *
 * The whole text rather than a digest, because it is a couple of kilobytes on a
 * table with tens of rows and it answers a question a hash cannot: *what* the
 * shipped version said, so a human deciding whether to take an update can be shown
 * the difference instead of a boolean.
 *
 * It exists because built-ins seed once per workspace as editable rows, which is
 * deliberate and had a consequence nobody had named: a change to a shipped persona
 * never reached a workspace that already had one. That is not cosmetic — the
 * `planner` built-in shipped with `tools: []`, the planner/worker trust boundary was later amended to give a
 * planner read-only tools precisely because the empty list made it stall on the
 * approval SLA, and every existing workspace kept the version that stalls.
 *
 * With this, "the human edited it" and "the platform shipped a new one" stop being
 * the same observation: a row whose markdown still hashes to what was seeded was
 * never touched, so it can be brought forward silently. Anything else is a human's
 * work and is left alone.
 */
 builtinSource: text('builtin_source'),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 updatedAt: timestamp('updated_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [
 index('agent_persona_workspace_idx').on(t.workspaceId),
 uniqueIndex('agent_persona_workspace_name_idx').on(t.workspaceId, t.name),
 ],
)

/**
 * The capability registry. Workspace-owned
 * and human-curated — which is the security story in one line: a capability is
 * something an operator added deliberately, never something a repository under
 * review can introduce.
 *
 * `toolListHash` is the "pinned tool-list hash for MCP". An MCP server decides
 * for itself what it exposes, so without a pin a server reviewed offering three
 * read-only tools can quietly start offering a fourth that writes.
 *
 * Skills store their `content` here rather than on any run's disk, because with
 * `settingSources: []` a skill in the clone is content the agent can write — see
 * packages/domain/src/capabilities.ts for why that settles the roadmap vs the capability registry — capability attachment.
 */
export const capability = pgTable(
 'capability',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 kind: text('kind').notNull,
 name: text('name').notNull,
 description: text('description').notNull.default(''),
 transport: text('transport'),
 command: text('command'),
 args: jsonb('args').$type<string[]>.notNull.default([]),
 url: text('url'),
 toolListHash: text('tool_list_hash'),
 content: text('content'),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 updatedAt: timestamp('updated_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [
 index('capability_workspace_idx').on(t.workspaceId),
 uniqueIndex('capability_workspace_name_idx').on(t.workspaceId, t.name),
 ],
)

/**
 * The `persona_capability` join table, "with per-attachment scopes" — which is
 * why this is a table rather than a jsonb array on the persona, unlike
 * `personaGroup.personaIds`.
 */
export const personaCapability = pgTable(
 'persona_capability',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 personaId: uuid('persona_id')
.notNull
.references( => agentPersona.id, { onDelete: 'cascade' }),
 capabilityId: uuid('capability_id')
.notNull
.references( => capability.id, { onDelete: 'cascade' }),
 // Empty means "everything this capability offers". Narrowing here is what
 // makes attenuation on a child's scope meaningful.
 allowedTools: jsonb('allowed_tools').$type<string[]>.notNull.default([]),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [
 index('persona_capability_persona_idx').on(t.workspaceId, t.personaId),
 uniqueIndex('persona_capability_unique_idx').on(t.personaId, t.capabilityId),
 ],
)

/**
 * Organizational persona grouping — a jsonb array of member
 * persona ids, same convention as `agentPersona.tools`. No join table: there
 * is no per-attachment metadata, unlike `persona_capability`.
 */
export const personaGroup = pgTable(
 'persona_group',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 name: text('name').notNull,
 personaIds: jsonb('persona_ids').$type<string[]>.notNull.default([]),
 /**
 * Where each member sits on the composition canvas, keyed by persona id.
 *
 * Persisted rather than laid out on open, because on an authoring canvas
 * **position is a fact**. A human who arranged a team around a lead
 * planner has recorded an intent; recomputing it on the next open would throw
 * that away every time.
 *
 * A member with no entry is placed by the client on first open and saved with the
 * next edit — so adding a persona through any other surface is not a broken row.
 */
 layout: jsonb('layout')
.$type<Record<string, { x: number; y: number }>>
.notNull
.default({}),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 updatedAt: timestamp('updated_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [
 index('persona_group_workspace_idx').on(t.workspaceId),
 uniqueIndex('persona_group_workspace_name_idx').on(t.workspaceId, t.name),
 ],
)

/**
 * `toolName`/`input` are the exact argv the SDK is about to run — never a
 * model-authored summary. `resolvedBy` must be a `user`
 * actor; enforced in the use-case, not the schema.
 */
export const approvalRequest = pgTable(
 'approval_request',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 agentRunId: uuid('agent_run_id')
.notNull
.references( => agentRun.id, { onDelete: 'cascade' }),
 toolUseId: text('tool_use_id').notNull,
 toolName: text('tool_name').notNull,
 input: jsonb('input').notNull,
 status: text('status').notNull.default('pending'),
 // No hard FK, deliberately: same reasoning as the actor columns above —
 // devAuth-based tests use synthetic user ids never inserted into
 // Better Auth's `user` table, and a resolver's identity here is an audit
 // fact that must survive even if the referenced user is later removed.
 resolvedByUserId: text('resolved_by_user_id'),
 /**
 * A clarifying question, when this gate is one
 * rather than a tool call.
 *
 * Mid-flight steering: "a clarifying question is that same gate carrying a prompt and returning a
 * string. Reuse it rather than build a second blocking channel" — so this is two
 * nullable columns on the proven mechanism rather than a second table with its own
 * SLA, its own notification path and its own identity rules to get wrong.
 *
 * `question` is **model-authored**, so it is attacker-controllable text and must render inside the untrusted fence. `answer` is a human's
 * and is trusted input. Null on an ordinary tool gate, which is what distinguishes
 * the two kinds without a discriminator column that could disagree with them.
 */
 question: text('question'),
 answer: text('answer'),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 resolvedAt: timestamp('resolved_at', { withTimezone: true }),
 },
 (t) => [
 index('approval_request_run_idx').on(t.agentRunId),
 uniqueIndex('approval_request_tool_use_idx').on(t.agentRunId, t.toolUseId),
 ],
)

/**
 * `seq` is the ordering and pagination key. Timestamps collide under concurrent
 * inserts, so cursors must never be built from `created_at`.
 */
export const message = pgTable(
 'message',
 {
 id: uuid('id').primaryKey.defaultRandom,
 seq: bigserial('seq', { mode: 'bigint' }).notNull,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 threadId: uuid('thread_id')
.notNull
.references( => thread.id, { onDelete: 'cascade' }),
 // Polymorphic actor columns, deliberately without a hard FK on either side
 // (mirrors audit_event below): a cascade delete on `agent_run` or `user`
 // must not silently corrupt chat history. Consistency is enforced in the
 // mapper layer (packages/db/src/mappers.ts toActor/fromActor).
 actorKind: text('actor_kind').notNull,
 actorUserId: text('actor_user_id'),
 actorAgentRunId: uuid('actor_agent_run_id'),
 bodyKind: text('body_kind').notNull,
 bodyText: text('body_text').notNull,
 // The SDK's correlation id for a tool call and its result, so a reader can pair
 // them without guessing. Nullable and unindexed on purpose: it is null for every
 // other kind of message, and the only consumer holds one loaded page in memory
 // and joins on it there — a column, not a lookup key.
 toolUseId: text('tool_use_id'),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 editedAt: timestamp('edited_at', { withTimezone: true }),
 },
 (t) => [
 index('message_thread_seq_idx').on(t.workspaceId, t.threadId, t.seq),
 uniqueIndex('message_seq_idx').on(t.seq),
 ],
)

/**
 * Where a human can be reached. One row per registered destination — for web push, one
 * per browser profile that granted permission.
 *
 * `endpoint` is the target's identity, so re-registering the same browser
 * upserts rather than accumulating stale rows. Unique per workspace rather than
 * globally: the same browser may legitimately be registered in two workspaces,
 * and delivery is always workspace-scoped.
 *
 * No hard FK on `user_id`, same convention as `approval_request.resolved_by_user_id`:
 * devAuth-based tests use synthetic user ids that never reach Better Auth's `user`
 * table.
 */
export const notificationTarget = pgTable(
 'notification_target',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 userId: text('user_id').notNull,
 transport: text('transport').notNull,
 endpoint: text('endpoint').notNull,
 // Transport-specific and opaque to everything but the adapter — for web
 // push, the subscription's p256dh/auth keys (RFC 8291).
 credentials: jsonb('credentials').$type<Record<string, string>>.notNull.default({}),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [
 index('notification_target_workspace_idx').on(t.workspaceId),
 uniqueIndex('notification_target_endpoint_idx').on(t.workspaceId, t.endpoint),
 ],
)

/**
 * The worker-notes ledger — the shared context a swarm's runs
 * read, and the same data the Phase 2 kanban is a board rendering of.
 *
 * **Not in the repository, and that is the design.** the worker-notes design: "If each run wrote
 * notes into its own clone, every note would become part of every diff and pass
 * through the merge queue — so note-writing would itself manufacture the conflicts
 * this is meant to reduce." Hence a table here, workspace-side.
 *
 * `treeRunId` is the key everything reads by: a Planner run, or a parentless run
 * being its own root. Denormalized onto the row rather than resolved by walking
 * `parent_run_id` at read time, because assembling a starting run's context must be
 * one indexed lookup, and because a swarm's siblings are all one hop from the root
 * anyway.
 *
 * `agentRunId` is nullable and set-null rather than cascade: a note is meant to
 * outlive the ephemeral run that wrote it, and a human's note is about the tree
 * rather than any one run.
 *
 * `seq` exists for the reason `message.seq` and `merge_queue_entry.position` do —
 * a swarm's workers write notes in the same millisecond, so `created_at` cannot
 * order them, and the render order of a ledger is what a worker reads as recency.
 */
export const workerNote = pgTable(
 'worker_note',
 {
 id: uuid('id').primaryKey.defaultRandom,
 seq: bigserial('seq', { mode: 'bigint' }).notNull,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 treeRunId: uuid('tree_run_id')
.notNull
.references(: AnyPgColumn => agentRun.id, { onDelete: 'cascade' }),
 agentRunId: uuid('agent_run_id').references(: AnyPgColumn => agentRun.id, {
 onDelete: 'set null',
 }),
 // 'platform' | 'human' | 'agent_run'. The only distinction that carries security
 // weight is agent_run versus the other two — see renderNotesForPrompt.
 authorKind: text('author_kind').notNull,
 kind: text('kind').notNull,
 title: text('title').notNull,
 body: text('body').notNull,
 paths: jsonb('paths').$type<string[]>.notNull.default([]),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [
 index('worker_note_tree_idx').on(t.workspaceId, t.treeRunId, t.seq),
 // Backs the per-run write cap, which is what stops a looping agent turning the
 // ledger into a denial of service against every sibling's context window.
 index('worker_note_run_idx').on(t.workspaceId, t.agentRunId),
 ],
)

/** Append-only. No update or delete path exists by design. */
export const auditEvent = pgTable(
 'audit_event',
 {
 id: uuid('id').primaryKey.defaultRandom,
 seq: bigserial('seq', { mode: 'bigint' }).notNull,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 actorKind: text('actor_kind').notNull,
 actorUserId: text('actor_user_id'),
 actorAgentRunId: uuid('actor_agent_run_id'),
 action: text('action').notNull,
 subjectType: text('subject_type').notNull,
 subjectId: text('subject_id').notNull,
 metadata: jsonb('metadata').notNull.default({}),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [index('audit_workspace_seq_idx').on(t.workspaceId, t.seq)],
)

/**
 * A subtask a Planner submitted that is waiting on another.
 *
 * **Its own table rather than an `agent_run` in a new status**, and that is the
 * load-bearing decision. The worker-notes design says "a card *is* a run", which argues for
 * modelling a waiting subtask as a blocked run — but a run row is what the
 * concurrency limit counts, what the reaper sweeps, what the kill switch cancels and
 * what a Runner declares resumable on reconnect. A row that is none of those things
 * while looking like all of them would need every one of those invariants amended,
 * and each amendment is a place a real run could later be skipped.
 *
 * So: a subtask is not a run until it starts. When it starts it goes through
 * `startPlannedChild` unchanged, which is what keeps the attenuation, the depth
 * limit and the concurrency limit on exactly one path.
 *
 * Rows are terminal once `status` leaves `waiting`; nothing updates a started or
 * skipped subtask again, so this doubles as the record of *why* a subtask never ran.
 */
export const planSubtask = pgTable(
 'plan_subtask',
 {
 id: uuid('id').primaryKey.defaultRandom,
 workspaceId: uuid('workspace_id')
.notNull
.references( => workspace.id, { onDelete: 'cascade' }),
 /** The planner run whose decomposition this came from. */
 plannerRunId: uuid('planner_run_id')
.notNull
.references(: AnyPgColumn => agentRun.id, { onDelete: 'cascade' }),
 /**
 * Index within that decomposition. `dependsOn` holds these same numbers, so the
 * edges stay meaningful without a second identifier the model would have to
 * reproduce.
 */
 position: integer('position').notNull,
 title: text('title').notNull,
 task: text('task').notNull,
 personaName: text('persona_name').notNull,
 paths: jsonb('paths').$type<string[]>.notNull.default([]),
 dependsOn: jsonb('depends_on').$type<number[]>.notNull.default([]),
 /** 'waiting' | 'started' | 'skipped' | 'refused'. */
 status: text('status').notNull.default('waiting'),
 /** Set when `status` becomes 'started'. */
 agentRunId: uuid('agent_run_id').references(: AnyPgColumn => agentRun.id, {
 onDelete: 'set null',
 }),
 /** Why it was skipped or refused — shown to the human, never re-derived. */
 detail: text('detail'),
 createdAt: timestamp('created_at', { withTimezone: true }).notNull.defaultNow,
 updatedAt: timestamp('updated_at', { withTimezone: true }).notNull.defaultNow,
 },
 (t) => [
 // One row per position per plan. This is also what makes recording a
 // decomposition idempotent: a replayed `plan_submitted` frame collides rather
 // than duplicating the whole pipeline.
 uniqueIndex('plan_subtask_position_idx').on(t.plannerRunId, t.position),
 index('plan_subtask_planner_idx').on(t.workspaceId, t.plannerRunId, t.status),
 ],
)
