import { sql } from 'drizzle-orm'
import {
  bigserial,
  boolean,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core'
import { user } from './auth-schema.js'

/**
 * Better Auth owns `user`, `session`, `account`, `verification`
 * (./auth-schema.ts, generated by `@better-auth/cli` — do not hand-edit, see
 * apps/server/better-auth.config.ts). Everything below is domain-owned and
 * references `user.id` where identity matters.
 */

export const workspace = pgTable(
  'workspace',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    // Global kill switch (PLAN.md §6 runtime safety). Persisted rather than
    // held in memory so a pause survives a server restart — an operator who
    // stopped everything must not have it silently undone by a redeploy.
    runsPaused: boolean('runs_paused').notNull().default(false),
    runsPausedAt: timestamp('runs_paused_at', { withTimezone: true }),
    // No hard FK, same reasoning as approvalRequest.resolvedByUserId: who hit
    // the switch is an audit fact that must survive the user being removed.
    runsPausedByUserId: text('runs_paused_by_user_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('workspace_slug_idx').on(t.slug)],
)

export const workspaceMember = pgTable(
  'workspace_member',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    role: text('role').notNull().default('member'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('workspace_member_unique_idx').on(t.workspaceId, t.userId)],
)

export const channel = pgTable(
  'channel',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    topic: text('topic'),
    isPrivate: boolean('is_private').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('channel_workspace_name_idx').on(t.workspaceId, t.name)],
)

export const thread = pgTable(
  'thread',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    channelId: uuid('channel_id')
      .notNull()
      .references(() => channel.id, { onDelete: 'cascade' }),
    parentMessageId: uuid('parent_message_id'),
    isRoot: boolean('is_root').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('thread_channel_idx').on(t.workspaceId, t.channelId),
    // At most one root thread per channel, enforced in the database.
    uniqueIndex('thread_root_per_channel_idx')
      .on(t.channelId)
      .where(sql`${t.isRoot}`),
  ],
)

/** A paired local daemon (PLAN.md §4a). `allowedRoots` is Runner-declared, not server-managed. */
export const runner = pgTable(
  'runner',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    // Hashed, not raw — a leaked DB row must not itself be a usable pairing token.
    pairingTokenHash: text('pairing_token_hash').notNull(),
    allowedRoots: jsonb('allowed_roots').$type<string[]>().notNull().default([]),
    connected: boolean('connected').notNull().default(false),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('runner_workspace_idx').on(t.workspaceId),
    uniqueIndex('runner_pairing_token_hash_idx').on(t.pairingTokenHash),
  ],
)

/** Phase 1 scope cut (PLAN.md §5a): bound by absolute path, no directory picker or `git init` flow yet. */
export const repository = pgTable(
  'repository',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    runnerId: uuid('runner_id')
      .notNull()
      .references(() => runner.id, { onDelete: 'cascade' }),
    displayName: text('display_name').notNull(),
    absolutePath: text('absolute_path').notNull(),
    defaultBranch: text('default_branch').notNull(),
    // What the merge queue runs against a rebased branch before merging it
    // (PLAN.md §7 Phase 2's "run tests"). Null merges unverified — see
    // `planMergeVerification`, which also explains why this executes in the
    // sandbox: the command is the operator's, but the code it runs is the
    // agent's.
    verifyCommand: text('verify_command'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('repository_workspace_idx').on(t.workspaceId)],
)

/**
 * `persona` is inline JSON for Phase 1 — no markdown/git-backed persona
 * storage yet (PLAN.md §4/§4e describe the eventual format).
 */
export const agentRun = pgTable(
  'agent_run',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    threadId: uuid('thread_id')
      .notNull()
      .references(() => thread.id, { onDelete: 'cascade' }),
    repositoryId: uuid('repository_id')
      .notNull()
      .references(() => repository.id, { onDelete: 'cascade' }),
    runnerId: uuid('runner_id')
      .notNull()
      .references(() => runner.id, { onDelete: 'cascade' }),
    persona: jsonb('persona').notNull(),
    // Swarm structure (PLAN.md §5, Phase 2). Null for a run a human started.
    // `relation` distinguishes delegation from review/reconcile, which §5 is
    // explicit should not masquerade as delegation children. Self-referencing FK
    // declared via a callback because the table is still being defined here.
    parentRunId: uuid('parent_run_id').references((): AnyPgColumn => agentRun.id, {
      onDelete: 'cascade',
    }),
    relation: text('relation'),
    status: text('status').notNull().default('pending'),
    totalCostUsd: doublePrecision('total_cost_usd'),
    errorMessage: text('error_message'),
    // Set once the Runner finishes cloning (PLAN.md §5a) — null until then,
    // and for any run that fails before a workspace is ever prepared.
    clonePath: text('clone_path'),
    branchName: text('branch_name'),
    // Set by a human's end-of-run keep/discard decision on DiffView (PLAN.md
    // §7 ship criterion) — null until then. `discarded` also implies the
    // clone on disk has been removed by the Runner.
    branchDisposition: text('branch_disposition'),
    // Dead-run reaper inputs (PLAN.md §6 runtime safety) — internal-only,
    // never exposed through the contract. `lastHeartbeatAt` is bumped only by
    // the Runner's periodic heartbeat frame (detects a dead connection);
    // `lastEventAt` is bumped by any agent_event (detects a hung-but-connected
    // run). Both null until first arrival — the reaper falls back to
    // `createdAt` so a run that never gets a first heartbeat/event is still
    // caught, not ignored forever.
    lastHeartbeatAt: timestamp('last_heartbeat_at', { withTimezone: true }),
    lastEventAt: timestamp('last_event_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
  },
  (t) => [
    index('agent_run_thread_idx').on(t.workspaceId, t.threadId),
    // Backs the tree view's per-parent lookup (PLAN.md §3 Views, Phase 2).
    index('agent_run_parent_idx').on(t.workspaceId, t.parentRunId),
  ],
)

/**
 * The structured event tier (PLAN.md §4d-bis: "Postgres, append-only, indexed
 * by run"), doubling as the idempotency ledger for event ingest (§6 runtime
 * safety: "idempotency keys on run steps").
 *
 * `seq` is a per-run counter the Runner assigns. The unique index on
 * (agent_run_id, seq) is the whole mechanism: a retransmitted or replayed event
 * conflicts, the insert no-ops, and `recordAgentEvent` skips it — so a
 * reconnect can never double-append the same tool call into a thread.
 *
 * Deliberately not the stream-only tier: token deltas and partial reasoning
 * never reach here (§4d-bis), and the verbatim provider transcript is a separate
 * blob-storage concern that is still deferred past Phase 1.
 */
export const agentRunEvent = pgTable(
  'agent_run_event',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    agentRunId: uuid('agent_run_id')
      .notNull()
      .references(() => agentRun.id, { onDelete: 'cascade' }),
    seq: integer('seq').notNull(),
    kind: text('kind').notNull(),
    payload: jsonb('payload').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('agent_run_event_run_seq_idx').on(t.agentRunId, t.seq),
    index('agent_run_event_workspace_run_idx').on(t.workspaceId, t.agentRunId, t.seq),
  ],
)

/**
 * The serialized merge queue (PLAN.md §7 Phase 2, §5a). One row per branch a
 * human queued for merge into its repository's default branch.
 *
 * Two indexes carry the invariants rather than leaving them to application code:
 *
 * - `merge_queue_active_per_repo_idx` — **at most one `merging` entry per
 *   repository**. This is the serialization, and it is here rather than in the
 *   sweep because two servers sweeping concurrently would both read the same
 *   queued entry and both try to claim it. One insert wins; the other's claim
 *   fails, which is exactly right.
 * - `merge_queue_open_per_run_idx` — a run may have at most one *open* entry, so
 *   double-clicking Merge cannot queue the same branch twice. Terminal entries are
 *   exempt: a branch that failed and was re-queued is a second, legitimate attempt.
 *
 * `position` is a bigserial for the reason `message.seq` is: a swarm's siblings are
 * queued in the same millisecond, so `created_at` cannot order them.
 */
export const mergeQueueEntry = pgTable(
  'merge_queue_entry',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    position: bigserial('position', { mode: 'bigint' }).notNull(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    repositoryId: uuid('repository_id')
      .notNull()
      .references(() => repository.id, { onDelete: 'cascade' }),
    agentRunId: uuid('agent_run_id')
      .notNull()
      .references(() => agentRun.id, { onDelete: 'cascade' }),
    // Snapshotted at enqueue time, so an entry still says which branch it was
    // about even after the run's own row changes underneath it.
    branchName: text('branch_name').notNull(),
    status: text('status').notNull().default('queued'),
    failureReason: text('failure_reason'),
    detail: text('detail'),
    mergedCommitSha: text('merged_commit_sha'),
    // Whether a verification command actually ran and passed — not whether one was
    // configured. A repository with no command merges unverified, and this says so.
    verified: boolean('verified').notNull().default(false),
    // No hard FK, same convention as approvalRequest.resolvedByUserId: who queued a
    // merge is an audit fact that must survive the user being removed.
    enqueuedByUserId: text('enqueued_by_user_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
  },
  (t) => [
    index('merge_queue_repo_idx').on(t.workspaceId, t.repositoryId, t.position),
    uniqueIndex('merge_queue_active_per_repo_idx')
      .on(t.repositoryId)
      .where(sql`${t.status} = 'merging'`),
    uniqueIndex('merge_queue_open_per_run_idx')
      .on(t.agentRunId)
      .where(sql`${t.status} in ('queued', 'merging')`),
  ],
)

/**
 * Persona storage (PLAN.md §4e, Phase 1 subset — read/CRUD only, no
 * git-backed versioning yet, per HANDOFF.md). `markdownSource` is the source
 * of truth; the other columns are its parsed frontmatter, denormalized for
 * querying without re-parsing on every list/get.
 */
export const agentPersona = pgTable(
  'agent_persona',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    description: text('description').notNull(),
    markdownSource: text('markdown_source').notNull(),
    model: text('model').notNull(),
    tools: jsonb('tools').$type<string[]>().notNull().default([]),
    harnessEffort: text('harness_effort'),
    harnessMaxTurns: doublePrecision('harness_max_turns'),
    harnessAutoApprove: boolean('harness_auto_approve').notNull().default(false),
    // Enforced at the egress proxy, not advisory (PLAN.md §6/§9). Null = uncapped.
    harnessBudgetCapUsd: doublePrecision('harness_budget_cap_usd'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('agent_persona_workspace_idx').on(t.workspaceId),
    uniqueIndex('agent_persona_workspace_name_idx').on(t.workspaceId, t.name),
  ],
)

/**
 * Organizational persona grouping (PLAN.md §3a) — a jsonb array of member
 * persona ids, same convention as `agentPersona.tools`. No join table: there
 * is no per-attachment metadata, unlike `persona_capability` (§4e, Phase 2).
 */
export const personaGroup = pgTable(
  'persona_group',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    personaIds: jsonb('persona_ids').$type<string[]>().notNull().default([]),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('persona_group_workspace_idx').on(t.workspaceId),
    uniqueIndex('persona_group_workspace_name_idx').on(t.workspaceId, t.name),
  ],
)

/**
 * `toolName`/`input` are the exact argv the SDK is about to run — never a
 * model-authored summary (PLAN.md §6 A1/A3). `resolvedBy` must be a `user`
 * actor; enforced in the use-case, not the schema.
 */
export const approvalRequest = pgTable(
  'approval_request',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    agentRunId: uuid('agent_run_id')
      .notNull()
      .references(() => agentRun.id, { onDelete: 'cascade' }),
    toolUseId: text('tool_use_id').notNull(),
    toolName: text('tool_name').notNull(),
    input: jsonb('input').notNull(),
    status: text('status').notNull().default('pending'),
    // No hard FK, deliberately: same reasoning as the actor columns above —
    // devAuth-based tests use synthetic user ids never inserted into
    // Better Auth's `user` table, and a resolver's identity here is an audit
    // fact that must survive even if the referenced user is later removed.
    resolvedByUserId: text('resolved_by_user_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  },
  (t) => [
    index('approval_request_run_idx').on(t.agentRunId),
    uniqueIndex('approval_request_tool_use_idx').on(t.agentRunId, t.toolUseId),
  ],
)

/**
 * `seq` is the ordering and pagination key. Timestamps collide under concurrent
 * inserts, so cursors must never be built from `created_at`.
 */
export const message = pgTable(
  'message',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    seq: bigserial('seq', { mode: 'bigint' }).notNull(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    threadId: uuid('thread_id')
      .notNull()
      .references(() => thread.id, { onDelete: 'cascade' }),
    // Polymorphic actor columns, deliberately without a hard FK on either side
    // (mirrors audit_event below): a cascade delete on `agent_run` or `user`
    // must not silently corrupt chat history. Consistency is enforced in the
    // mapper layer (packages/db/src/mappers.ts toActor/fromActor).
    actorKind: text('actor_kind').notNull(),
    actorUserId: text('actor_user_id'),
    actorAgentRunId: uuid('actor_agent_run_id'),
    bodyKind: text('body_kind').notNull(),
    bodyText: text('body_text').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    editedAt: timestamp('edited_at', { withTimezone: true }),
  },
  (t) => [
    index('message_thread_seq_idx').on(t.workspaceId, t.threadId, t.seq),
    uniqueIndex('message_seq_idx').on(t.seq),
  ],
)

/**
 * Where a human can be reached (PLAN.md §3's notification half, §4a's
 * `NotificationPort`). One row per registered destination — for web push, one
 * per browser profile that granted permission.
 *
 * `endpoint` is the target's identity, so re-registering the same browser
 * upserts rather than accumulating stale rows. Unique per workspace rather than
 * globally: the same browser may legitimately be registered in two workspaces,
 * and delivery is always workspace-scoped.
 *
 * No hard FK on `user_id`, same convention as `approval_request.resolved_by_user_id`:
 * devAuth-based tests use synthetic user ids that never reach Better Auth's `user`
 * table.
 */
export const notificationTarget = pgTable(
  'notification_target',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    userId: text('user_id').notNull(),
    transport: text('transport').notNull(),
    endpoint: text('endpoint').notNull(),
    // Transport-specific and opaque to everything but the adapter — for web
    // push, the subscription's p256dh/auth keys (RFC 8291).
    credentials: jsonb('credentials').$type<Record<string, string>>().notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('notification_target_workspace_idx').on(t.workspaceId),
    uniqueIndex('notification_target_endpoint_idx').on(t.workspaceId, t.endpoint),
  ],
)

/** Append-only. No update or delete path exists by design (PLAN.md §5). */
export const auditEvent = pgTable(
  'audit_event',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    seq: bigserial('seq', { mode: 'bigint' }).notNull(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspace.id, { onDelete: 'cascade' }),
    actorKind: text('actor_kind').notNull(),
    actorUserId: text('actor_user_id'),
    actorAgentRunId: uuid('actor_agent_run_id'),
    action: text('action').notNull(),
    subjectType: text('subject_type').notNull(),
    subjectId: text('subject_id').notNull(),
    metadata: jsonb('metadata').notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('audit_workspace_seq_idx').on(t.workspaceId, t.seq)],
)
