import { drizzleAdapter } from '@better-auth/drizzle-adapter'
import type { Database } from '@loom/db'
import { betterAuth } from 'better-auth'

/**
 * Better Auth owns its own tables (user, session, account, verification) —
 * see packages/db/src/auth-schema.ts, generated by `@better-auth/cli`, not
 * hand-written.
 *
 * It does NOT own workspace/workspace_member — those are domain-owned tables
 * (packages/db/src/schema.ts) that this module's identity resolution joins
 * against in auth.ts.
 */
export const createBetterAuth = (options: {
 db: Database
 secret: string
 baseUrl: string
 webOrigin: string
}) =>
 betterAuth({
 database: drizzleAdapter(options.db, { provider: 'pg' }),
 secret: options.secret,
 baseURL: options.baseUrl,
 trustedOrigins: [options.webOrigin],
 emailAndPassword: {
 enabled: true,
 },
 })

export type LoomAuth = ReturnType<typeof createBetterAuth>
